import { z } from 'zod';

export const pricingEntrySchema = z
  .object({
    provider: z.enum(['anthropic', 'openai', 'google']),
    model: z.string().min(1),
    inputUsdPerMillion: z.number().nonnegative(),
    outputUsdPerMillion: z.number().nonnegative(),
    cacheReadUsdPerMillion: z.number().nonnegative(),
    cacheWriteUsdPerMillion: z.number().nonnegative(),
    verifiedAt: z.string().date(),
    sourceUrl: z.string().url(),
  })
  .strict();

export type PricingEntry = z.infer<typeof pricingEntrySchema>;

// [ASSUMPTION-RESOLVED: Use the 2026-05-05 Track-1 catalog snapshot for Milestone 1; pricing:check enforces freshness before publish.]
export const DEFAULT_CATALOG = [
  {
    provider: 'anthropic',
    model: 'claude-sonnet-4',
    inputUsdPerMillion: 3,
    outputUsdPerMillion: 15,
    cacheReadUsdPerMillion: 0.3,
    cacheWriteUsdPerMillion: 3.75,
    verifiedAt: '2026-05-05',
    sourceUrl: 'https://docs.anthropic.com/en/docs/about-claude/pricing',
  },
  {
    provider: 'anthropic',
    model: 'claude-opus-4',
    inputUsdPerMillion: 15,
    outputUsdPerMillion: 75,
    cacheReadUsdPerMillion: 1.5,
    cacheWriteUsdPerMillion: 18.75,
    verifiedAt: '2026-05-05',
    sourceUrl: 'https://docs.anthropic.com/en/docs/about-claude/pricing',
  },
  {
    provider: 'anthropic',
    model: 'claude-haiku-4-5',
    inputUsdPerMillion: 0.8,
    outputUsdPerMillion: 4,
    cacheReadUsdPerMillion: 0.08,
    cacheWriteUsdPerMillion: 1,
    verifiedAt: '2026-05-05',
    sourceUrl: 'https://docs.anthropic.com/en/docs/about-claude/pricing',
  },
  {
    provider: 'anthropic',
    model: 'claude-3-5-sonnet',
    inputUsdPerMillion: 3,
    outputUsdPerMillion: 15,
    cacheReadUsdPerMillion: 0.3,
    cacheWriteUsdPerMillion: 3.75,
    verifiedAt: '2026-05-05',
    sourceUrl: 'https://docs.anthropic.com/en/docs/about-claude/pricing',
  },
  {
    provider: 'anthropic',
    model: 'claude-3-5-haiku',
    inputUsdPerMillion: 0.8,
    outputUsdPerMillion: 4,
    cacheReadUsdPerMillion: 0.08,
    cacheWriteUsdPerMillion: 1,
    verifiedAt: '2026-05-05',
    sourceUrl: 'https://docs.anthropic.com/en/docs/about-claude/pricing',
  },
  {
    provider: 'openai',
    model: 'gpt-5',
    inputUsdPerMillion: 1.25,
    outputUsdPerMillion: 10,
    cacheReadUsdPerMillion: 0.125,
    cacheWriteUsdPerMillion: 0,
    verifiedAt: '2026-05-05',
    sourceUrl: 'https://openai.com/api/pricing/',
  },
  {
    provider: 'openai',
    model: 'gpt-4.1',
    inputUsdPerMillion: 2,
    outputUsdPerMillion: 8,
    cacheReadUsdPerMillion: 0.5,
    cacheWriteUsdPerMillion: 0,
    verifiedAt: '2026-05-05',
    sourceUrl: 'https://openai.com/api/pricing/',
  },
  {
    provider: 'google',
    model: 'gemini-2.5-pro',
    inputUsdPerMillion: 1.25,
    outputUsdPerMillion: 10,
    cacheReadUsdPerMillion: 0.31,
    cacheWriteUsdPerMillion: 0,
    verifiedAt: '2026-05-05',
    sourceUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
  },
  {
    provider: 'google',
    model: 'gemini-2.5-flash',
    inputUsdPerMillion: 0.3,
    outputUsdPerMillion: 2.5,
    cacheReadUsdPerMillion: 0.075,
    cacheWriteUsdPerMillion: 0,
    verifiedAt: '2026-05-05',
    sourceUrl: 'https://ai.google.dev/gemini-api/docs/pricing',
  },
] satisfies PricingEntry[];
